# First we import numpy for working with numbers and sklearn for working with machine learning. We also get the dataset which is iris from the sklearn.datasets library

In [29]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

In [30]:
iris = load_iris()

# Lets look at the data. Features are the variables we will be using to predict the Target. The features are sizes of flowers and the targets at different types of flowers.

In [31]:
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0


# We take 3 rows out of the data to use later as testing data. These are one example of each flower.

In [32]:
test_idx = [0,50,100]

training data

In [33]:
training_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

testing data

In [45]:
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

# Generate random data for decision tree

In [39]:
model = tree.DecisionTreeClassifier()
model.fit(train_data, training_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

# Next we use the test data to see if it worked.

In [48]:
print(test_target)
print(model.predict(test_data))

[0 1 2]
[0 1 2]


Visualization

In [40]:
from sklearn.externals.six import StringIO
import pydotplus

In [41]:
dot_data = StringIO()
tree.export_graphviz(model, 
                    out_file=dot_data,
                    feature_names=iris.feature_names,
                    class_names=iris.target_names,
                    filled=True, rounded=True,
                    impurity=False)

In [49]:
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

In [50]:
graph.write_pdf("iris.pdf")

True